# This file was generated by GoReleaser. DO NOT EDIT.
class EcsLocal < Formula
  desc "Run ECS task definitions locally"
  homepage "https://github.com/Fullscreen/ecs-local"
  version "0.2.8"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/Fullscreen/ecs-local/releases/download/v0.2.8/ecs-local_Darwin_x86_64.tar.gz"
    sha256 "b6a1cf23d43ad282edb4ab09b271a6470a9b18b5ed4c05799377164cb89b4dc6"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/Fullscreen/ecs-local/releases/download/v0.2.8/ecs-local_Linux_x86_64.tar.gz"
      sha256 "ff2cae4c88fea329c5e295fccc15c098280316324fbc183cdca841d763260e00"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Fullscreen/ecs-local/releases/download/v0.2.8/ecs-local_Linux_arm64.tar.gz"
        sha256 "5864d26319b9c5922de3bd963a7391200945a8e1ce6d231d150faa08755b8e40"
      else
        url "https://github.com/Fullscreen/ecs-local/releases/download/v0.2.8/ecs-local_Linux_armv6.tar.gz"
        sha256 "964e8a4a23c5b2e8fa299d49a74b05b99ed1dd09e61a7ccfceb92bce516ad1de"
      end
    end
  end

  def install
    bin.install "ecs-local"
  end
end
