# This file was generated by GoReleaser. DO NOT EDIT.
class EcsLocal < Formula
  desc "Run ECS task definitions locally"
  homepage "https://github.com/Fullscreen/ecs-local"
  url "https://github.com/Fullscreen/ecs-local/releases/download/v0.2.4/ecs-local_Darwin_x86_64.tar.gz"
  version "0.2.4"
  sha256 "7376d0e2cbffe205c9ade2521818b7b65529d273563faa5d711daf8db3f5ffd5"

  def install
    bin.install "ecs-local"
  end
end
